// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: device.sql

package db

import (
	"context"
	"time"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices(
    device_name,
    device_manufacturer,
    device_origin,
    production_date,
    testing_date,
    device_model
)VALUES(
    $1,$2,$3,$4,$5,$6
) RETURNING id, device_name, device_manufacturer, device_origin, production_date, testing_date, device_model
`

type CreateDeviceParams struct {
	DeviceName         string    `json:"device_name"`
	DeviceManufacturer string    `json:"device_manufacturer"`
	DeviceOrigin       string    `json:"device_origin"`
	ProductionDate     time.Time `json:"production_date"`
	TestingDate        time.Time `json:"testing_date"`
	DeviceModel        string    `json:"device_model"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.DeviceName,
		arg.DeviceManufacturer,
		arg.DeviceOrigin,
		arg.ProductionDate,
		arg.TestingDate,
		arg.DeviceModel,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceName,
		&i.DeviceManufacturer,
		&i.DeviceOrigin,
		&i.ProductionDate,
		&i.TestingDate,
		&i.DeviceModel,
	)
	return i, err
}

const listDevice = `-- name: ListDevice :one
SELECT id, device_name, device_manufacturer, device_origin, production_date, testing_date, device_model FROM devices
WHERE id=$1 LIMIT 1
`

func (q *Queries) ListDevice(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRowContext(ctx, listDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceName,
		&i.DeviceManufacturer,
		&i.DeviceOrigin,
		&i.ProductionDate,
		&i.TestingDate,
		&i.DeviceModel,
	)
	return i, err
}

const listRecords = `-- name: ListRecords :many
SELECT devices.id, device_name, device_manufacturer, device_origin, production_date, testing_date, device_model, tests.id, test_name, tests.devices_id, tests.created_at, gear, percentage, lower_limit, upper_limit, test_data, results.id, test_id, results.devices_id, voltage, point_number, results.created_at, temperature, humidity
FROM devices
JOIN tests ON devices.id = tests.devices_id
JOIN results ON devices.id = results.devices_id 
WHERE devices.id = $1 AND results.id =  tests.id
`

type ListRecordsRow struct {
	ID                 int64     `json:"id"`
	DeviceName         string    `json:"device_name"`
	DeviceManufacturer string    `json:"device_manufacturer"`
	DeviceOrigin       string    `json:"device_origin"`
	ProductionDate     time.Time `json:"production_date"`
	TestingDate        time.Time `json:"testing_date"`
	DeviceModel        string    `json:"device_model"`
	ID_2               int64     `json:"id_2"`
	TestName           string    `json:"test_name"`
	DevicesID          int64     `json:"devices_id"`
	CreatedAt          time.Time `json:"created_at"`
	Gear               int64     `json:"gear"`
	Percentage         int64     `json:"percentage"`
	LowerLimit         int64     `json:"lower_limit"`
	UpperLimit         int64     `json:"upper_limit"`
	TestData           int64     `json:"test_data"`
	ID_3               int64     `json:"id_3"`
	TestID             int64     `json:"test_id"`
	DevicesID_2        int64     `json:"devices_id_2"`
	Voltage            int64     `json:"voltage"`
	PointNumber        int64     `json:"point_number"`
	CreatedAt_2        time.Time `json:"created_at_2"`
	Temperature        int64     `json:"temperature"`
	Humidity           int64     `json:"humidity"`
}

func (q *Queries) ListRecords(ctx context.Context, id int64) ([]ListRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecords, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordsRow{}
	for rows.Next() {
		var i ListRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceName,
			&i.DeviceManufacturer,
			&i.DeviceOrigin,
			&i.ProductionDate,
			&i.TestingDate,
			&i.DeviceModel,
			&i.ID_2,
			&i.TestName,
			&i.DevicesID,
			&i.CreatedAt,
			&i.Gear,
			&i.Percentage,
			&i.LowerLimit,
			&i.UpperLimit,
			&i.TestData,
			&i.ID_3,
			&i.TestID,
			&i.DevicesID_2,
			&i.Voltage,
			&i.PointNumber,
			&i.CreatedAt_2,
			&i.Temperature,
			&i.Humidity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
